### ISSUE TITLE
Issue after upgrade to 5100

### ISSUE THREAD

**Issue by alexdelprete** [RIPE-NCC/ripe-atlas-software-probe#125]
I'm using a dockerized 5100 version (https://github.com/Jamesits/docker-ripe-atlas). Previous version was working great.

I started fresh with this one, but I can't make it register, here's the log and the docker-compose:

```console
[entrypoint.sh]: Setting option RXTXRPT="yes"
[entrypoint.sh]: Done
Reboot count is now 1
RESULT 9000 done 1742848641 dca632e136b5 STARTING ATLAS system initialized (reboot count 1)
RESULT 9000 done 1742848641 dca632e136b5 STARTING TELNETD LOCALLY
br-15675b5341bf: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.19.0.1  netmask 255.255.0.0  broadcast 172.19.255.255
        inet6 fe80::48d4:38ff:fe10:c312  prefixlen 64  scopeid 0x20<link>
        ether 4a:d4:38:10:c3:12  txqueuelen 0  (Ethernet)
        RX packets 861  bytes 296923 (289.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 980  bytes 450860 (440.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 82:75:d7:8e:d9:92  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
end0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.10.29  netmask 255.255.254.0  broadcast 10.1.11.255
        inet6 fe80::dea6:32ff:fee1:36b5  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:e1:36:b5  txqueuelen 1000  (Ethernet)
        RX packets 30227  bytes 3257056 (3.1 MiB)
        RX errors 0  dropped 1353  overruns 0  frame 0
        TX packets 34274  bytes 17479139 (16.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 12973  bytes 789035 (770.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12973  bytes 789035 (770.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
veth0e25780: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::dcec:32ff:fe19:4e08  prefixlen 64  scopeid 0x20<link>
        ether de:ec:32:19:4e:08  txqueuelen 0  (Ethernet)
        RX packets 3  bytes 126 (126.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 35  bytes 4188 (4.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
vethce25729: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::2ccb:b8ff:feca:dbc1  prefixlen 64  scopeid 0x20<link>
        ether 2e:cb:b8:ca:db:c1  txqueuelen 0  (Ethernet)
        RX packets 613  bytes 209403 (204.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 745  bytes 428826 (418.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
vethea91256: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::8f4:51ff:fe5b:3a4b  prefixlen 64  scopeid 0x20<link>
        ether 0a:f4:51:5b:3a:4b  txqueuelen 0  (Ethernet)
        RX packets 245  bytes 99448 (97.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 276  bytes 26562 (25.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether dc:a6:32:e1:36:b6  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
RESULT 9006 done 1742848641 dca632e136b5 no reginit.vol start registration
/run/ripe-atlas/status/reginit.vol does not exist try new reg
Ping failed
start reg
ATLAS registration starting
REASON_FOR_REGISTRATION NEW NO previous state files
REGHOSTS reg02.atlas.ripe.net 193.0.19.25 2001:67c:2e8:11::c100:1319 reg01.atlas.ripe.net 193.0.19.12 2001:67c:2e8:11::c100:130c
ssh -p 443 atlas@reg02.atlas.ripe.net INIT
255  REGINIT exit with error
RESULT { "dst_name":"Issh-permission-denied.U964.Mdca632e136b5.sos.atlas.ripe.net", "ttr":0.000000, "af":6, "dst_addr":"2001:67c:2e8:3::c100:a4", "src_addr":"", "proto":"ICMP", "size":0, "result": [ { "error":"connect failed: Network is unreachable" } ] }
condmv: not moving, destination '/var/spool/ripe-atlas/data/out/simpleping' exists
```

```yaml
services:
  ripe-atlas:
    container_name: atlasprobe
    hostname: atlasprobe
    image: jamesits/ripe-atlas:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - RXTXRPT="yes"
      - TZ=Europe/Rome
    labels:
      - wud.watch=false
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/data/etc:/etc/ripe-atlas:rw
      - $PWD/data/status:/var/spool/ripe-atlas:rw
      - $PWD/data/probe:/run/ripe-atlas:rw
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - KILL
      - SETUID
      - SETGID
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
    mem_limit: "64000000000"
    mem_reservation: 64m
```
